### ISSUE TITLE
Store.get() no callback

### ISSUE THREAD

**Issue by MrFoxPro** [jasonmerino/react-native-simple-store#46] opened 2018-01-13 19:38 UTC
I dont know why but sometimes Store.get(key) just freezes.

**Comment by emstans** [comment] 2018-01-16 19:04
I've been running into this as well. I dug into it a little and it looks like an issue with the _reactNative.AsyncStorage call which is being wrapped, not the react-native-simple-store module.

From the module's implementation:

`get: function get(key) {
		if (!Array.isArray(key)) {
			return _reactNative.AsyncStorage.getItem(key).then(function (value) {
				return JSON.parse(value);
			});
		} else {
			return _reactNative.AsyncStorage.multiGet(key).then(function (values) {
				return values.map(function (value) {
					return JSON.parse(value[1]);
				});
			});
		}
	}`

The callback for getItem() is never invoked.

**Comment by MrFoxPro** [comment] 2018-01-16 19:16
@emstans Should we return null or empty object after `return _reactNative.AsyncStorage.getItem(key).then(function (value) {
				return JSON.parse(value);` ?

**Comment by MrFoxPro** [comment] 2018-01-16 19:18
@emstans Should we return null or empty object after `return _reactNative.AsyncStorage.getItem(key).then(function (value) {
				return JSON.parse(value);` ?

**Comment by jasonmerino** [comment] 2018-01-18 20:47
@MrFoxPro I may not be understanding your suggestion correctly, but adding a return statement after that code you pasted would not help anything as you can't have multiple returns in the same function.

Have you folks been able to reproduce this consistently? I've not ran across this behavior, but if you find a way to reproduce it I would like to help out fixing it up.

**Comment by MrFoxPro** [comment] 2018-01-19 04:22
You were right about return statement. I think we have to dive into asyncStorage module and understand how getItem() works

**Comment by jasonmerino** [comment] 2018-01-23 17:42
@MrFoxPro @emstans Sounds like this could be an upstream issue. Going to close this for now. If you think we should open it back up comment back and we can further diagnose.

**Closed by jasonmerino** 2018-01-23 17:42 UTC

**Comment by frenkelor** [comment] 2018-02-20 08:16
react native issue https://github.com/facebook/react-native/issues/14101

**Comment by emstans** [comment] 2018-02-20 17:12
Awesome, thanks for the update! Glad to know it wasn't just me :)
