### ISSUE TITLE
[Android] Please explain how this works

### ISSUE THREAD

**Issue by mihir-harbinger** [jasonmerino/react-native-simple-store#6] opened 2016-03-01 05:16 UTC
I did something like this- 

Inside signin component:
`store.save('credentials', {username: this.state.username, password: this.state.password});`

Inside home component: 

```
getData: function(){
    return store.get('credentials')
        .then((data) => {
            console.log(data);
            //return 'Username: ' + data.username + ' Password: ' + data.password;
        });
  }
```
it is returning 3 objects- 

```
Object {username: "android", password: "aa"}
Object {username: "android", password: "aa"}
Object {username: "android", password: "aa"}
```

Why is get() returning 3 objects? Is there anything wrong with the usage? Thank you in advance.

**Comment by jasonmerino** [comment] 2016-03-01 17:44
That's strange. Looks like you are using it correctly from what code you pasted above. Can you throw together a bare bones repo that reproduces the issue and push it up to Github?

**Comment by jasonmerino** [comment] 2016-03-24 20:40
@mihir-harbinger I'm going to be closing this out. If you are still having issues with it ping back and I'll reopen to help you debug it and find a fix.

**Closed by jasonmerino** 2016-03-24 20:40 UTC
