### ISSUE TITLE
I can't setState after getting object from storage

### ISSUE THREAD

**Issue by melihmucuk** [jasonmerino/react-native-simple-store#3] opened 2015-11-09 10:41 UTC
Hi, this code can't update state, how can I change state ? 
<pre><code>store.get('user').then((user) => {
  this.setState({user: user});
});</code></pre>

**Comment by jadsonlourenco** [comment] 2015-11-09 11:50
You can test with **self**:
```
var self = this;
store.get('user').then((user) => {
  self.setState({user: user});
});
```

**Comment by melihmucuk** [comment] 2015-11-09 11:55
nothing changed

**Comment by jasonmerino** [comment] 2015-11-09 19:24
@melihmucuk Can you verify that the `.then` function is being invoked. Since `.get` returns a promise there could be an error being thrown, in which case adding a `.catch` function might help you debug this.

```javascript
store.get('user').then((user) => {
  this.setState({user: user});
}).catch((error) => {
 // discover thrown error here
});
```

The library doesn't do anything to bind or change context and it should just rely on the ES6 arrow functions [lack of context](http://blog.getify.com/arrow-this/).

Beyond this, I'd need a more complete code sample replicating this. I'm using this library in an app and I am able to `.setState` in the `.then` function so I know that it is possible.

**Comment by jadsonlourenco** [comment] 2015-11-09 19:37
@melihmucuk I think you want to save an object to the new "state" then in that case your "state" needs to be an object:
```
this.state = {
  user: {}
};
```
So, for me works using **this** or **self**, I think the problem is that **"{}"**.

**Comment by jasonmerino** [comment] 2015-11-19 17:56
@melihmucuk I'm going to close this issue for now. If this is still giving you trouble and you can provide a bit larger example of the code I would be happy to revisit it and try and help you get this figured out.

**Closed by jasonmerino** 2015-11-19 17:56 UTC
